services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: m5nita
      POSTGRES_PASSWORD: m5nita
      POSTGRES_DB: m5nita
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: m5nita_test
      POSTGRES_PASSWORD: m5nita_test
      POSTGRES_DB: m5nita_test

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
