/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoolsPaymentSuccessRouteImport } from './routes/pools/payment-success'
import { Route as PoolsCreateRouteImport } from './routes/pools/create'
import { Route as InviteInviteCodeRouteImport } from './routes/invite/$inviteCode'
import { Route as PoolsPoolIdIndexRouteImport } from './routes/pools/$poolId/index'
import { Route as PoolsPoolIdRankingRouteImport } from './routes/pools/$poolId/ranking'
import { Route as PoolsPoolIdPredictionsRouteImport } from './routes/pools/$poolId/predictions'
import { Route as PoolsPoolIdManageRouteImport } from './routes/pools/$poolId/manage'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPaymentSuccessRoute = PoolsPaymentSuccessRouteImport.update({
  id: '/pools/payment-success',
  path: '/pools/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsCreateRoute = PoolsCreateRouteImport.update({
  id: '/pools/create',
  path: '/pools/create',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviteCodeRoute = InviteInviteCodeRouteImport.update({
  id: '/invite/$inviteCode',
  path: '/invite/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdIndexRoute = PoolsPoolIdIndexRouteImport.update({
  id: '/pools/$poolId/',
  path: '/pools/$poolId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdRankingRoute = PoolsPoolIdRankingRouteImport.update({
  id: '/pools/$poolId/ranking',
  path: '/pools/$poolId/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdPredictionsRoute = PoolsPoolIdPredictionsRouteImport.update({
  id: '/pools/$poolId/predictions',
  path: '/pools/$poolId/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdManageRoute = PoolsPoolIdManageRouteImport.update({
  id: '/pools/$poolId/manage',
  path: '/pools/$poolId/manage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
  '/invite/$inviteCode': typeof InviteInviteCodeRoute
  '/pools/create': typeof PoolsCreateRoute
  '/pools/payment-success': typeof PoolsPaymentSuccessRoute
  '/pools/$poolId/manage': typeof PoolsPoolIdManageRoute
  '/pools/$poolId/predictions': typeof PoolsPoolIdPredictionsRoute
  '/pools/$poolId/ranking': typeof PoolsPoolIdRankingRoute
  '/pools/$poolId/': typeof PoolsPoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
  '/invite/$inviteCode': typeof InviteInviteCodeRoute
  '/pools/create': typeof PoolsCreateRoute
  '/pools/payment-success': typeof PoolsPaymentSuccessRoute
  '/pools/$poolId/manage': typeof PoolsPoolIdManageRoute
  '/pools/$poolId/predictions': typeof PoolsPoolIdPredictionsRoute
  '/pools/$poolId/ranking': typeof PoolsPoolIdRankingRoute
  '/pools/$poolId': typeof PoolsPoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
  '/invite/$inviteCode': typeof InviteInviteCodeRoute
  '/pools/create': typeof PoolsCreateRoute
  '/pools/payment-success': typeof PoolsPaymentSuccessRoute
  '/pools/$poolId/manage': typeof PoolsPoolIdManageRoute
  '/pools/$poolId/predictions': typeof PoolsPoolIdPredictionsRoute
  '/pools/$poolId/ranking': typeof PoolsPoolIdRankingRoute
  '/pools/$poolId/': typeof PoolsPoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-profile'
    | '/login'
    | '/matches'
    | '/settings'
    | '/invite/$inviteCode'
    | '/pools/create'
    | '/pools/payment-success'
    | '/pools/$poolId/manage'
    | '/pools/$poolId/predictions'
    | '/pools/$poolId/ranking'
    | '/pools/$poolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/login'
    | '/matches'
    | '/settings'
    | '/invite/$inviteCode'
    | '/pools/create'
    | '/pools/payment-success'
    | '/pools/$poolId/manage'
    | '/pools/$poolId/predictions'
    | '/pools/$poolId/ranking'
    | '/pools/$poolId'
  id:
    | '__root__'
    | '/'
    | '/complete-profile'
    | '/login'
    | '/matches'
    | '/settings'
    | '/invite/$inviteCode'
    | '/pools/create'
    | '/pools/payment-success'
    | '/pools/$poolId/manage'
    | '/pools/$poolId/predictions'
    | '/pools/$poolId/ranking'
    | '/pools/$poolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  SettingsRoute: typeof SettingsRoute
  InviteInviteCodeRoute: typeof InviteInviteCodeRoute
  PoolsCreateRoute: typeof PoolsCreateRoute
  PoolsPaymentSuccessRoute: typeof PoolsPaymentSuccessRoute
  PoolsPoolIdManageRoute: typeof PoolsPoolIdManageRoute
  PoolsPoolIdPredictionsRoute: typeof PoolsPoolIdPredictionsRoute
  PoolsPoolIdRankingRoute: typeof PoolsPoolIdRankingRoute
  PoolsPoolIdIndexRoute: typeof PoolsPoolIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/payment-success': {
      id: '/pools/payment-success'
      path: '/pools/payment-success'
      fullPath: '/pools/payment-success'
      preLoaderRoute: typeof PoolsPaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/create': {
      id: '/pools/create'
      path: '/pools/create'
      fullPath: '/pools/create'
      preLoaderRoute: typeof PoolsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviteCode': {
      id: '/invite/$inviteCode'
      path: '/invite/$inviteCode'
      fullPath: '/invite/$inviteCode'
      preLoaderRoute: typeof InviteInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId/': {
      id: '/pools/$poolId/'
      path: '/pools/$poolId'
      fullPath: '/pools/$poolId/'
      preLoaderRoute: typeof PoolsPoolIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId/ranking': {
      id: '/pools/$poolId/ranking'
      path: '/pools/$poolId/ranking'
      fullPath: '/pools/$poolId/ranking'
      preLoaderRoute: typeof PoolsPoolIdRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId/predictions': {
      id: '/pools/$poolId/predictions'
      path: '/pools/$poolId/predictions'
      fullPath: '/pools/$poolId/predictions'
      preLoaderRoute: typeof PoolsPoolIdPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId/manage': {
      id: '/pools/$poolId/manage'
      path: '/pools/$poolId/manage'
      fullPath: '/pools/$poolId/manage'
      preLoaderRoute: typeof PoolsPoolIdManageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  SettingsRoute: SettingsRoute,
  InviteInviteCodeRoute: InviteInviteCodeRoute,
  PoolsCreateRoute: PoolsCreateRoute,
  PoolsPaymentSuccessRoute: PoolsPaymentSuccessRoute,
  PoolsPoolIdManageRoute: PoolsPoolIdManageRoute,
  PoolsPoolIdPredictionsRoute: PoolsPoolIdPredictionsRoute,
  PoolsPoolIdRankingRoute: PoolsPoolIdRankingRoute,
  PoolsPoolIdIndexRoute: PoolsPoolIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
